#pragma once

typedef enum status {
    SUCCESS,
    ERROR,
    ERROR_OUT_OF_RESOURCES,
    ERROR_REFCOUNT_OVERFLOW,
    ERROR_INVALID_QUEUE,
    ERROR_NOT_INITIALIZED,
    ERROR_INVALID_ARGUMENT,
    ERROR_INVALID_EXECUTABLE,
    ERROR_INVALID_CODE_OBJECT,
    ERROR_INVALID_ALLOCATION,
    ERROR_INVALID_AGENT,
    ERROR_INVALID_MEMORY_REGION,
    ERROR_INVALID_SYMBOL_NAME,
    ERROR_INVALID_FILE,
    ERROR_INVALID_CODE_OBJECT_READER,
    ERROR_INVALID_EXECUTABLE_SYMBOL,
    ERROR_INVALID_QUEUE_CREATION,
    ERROR_FROZEN_EXECUTABLE,
    ERROR_VARIABLE_ALREADY_DEFINED,
    ERROR_VARIABLE_UNDEFINED,
    STATUS_INFO_BREAK
} status_t;


